# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(max_length=2000),
        ),
    ]
