# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='mainapp.UserProfile'),
        ),
    ]
