# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180116_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
