# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_team_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='question',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
